<FirstScreen>:
    CustomLayout:
        Button:
            text: 'Forward'
            pos: root.width/2, root.height/2-self.height/2
            size: 200, 100
            on_release: root.manager.transition.direction = 'left'
            on_release: root.manager.current = 'Second'

<SecondScreen>:
    CustomLayout:
        Button:
            text: 'Back'
            pos: root.width/2-self.width, root.height/2-self.height/2
            size: 200, 100
            on_release: root.manager.transition.direction = 'right'
            on_release: root.manager.current = 'First'
        Button:
            text: 'Forward'
            pos: root.width/2, root.height/2-self.height/2
            size: 200, 100
            on_release: root.manager.transition.direction = 'left'
            on_release: root.manager.current = 'Third'

<ThirdScreen>:
    CustomLayout:
        Button:
            text: 'Back'
            pos: root.width/2-self.width, root.height/2-self.height/2
            size: 200, 100
            on_release: root.manager.transition.direction = 'right'
            on_release: root.manager.current = 'Second'
        Button:
            text: 'Forward'
            pos: root.width/2, root.height/2-self.height/2
            size: 200, 100
            on_release: root.manager.transition.direction = 'left'
            on_release: root.manager.current = 'Fourth'

<FourthScreen>:
    CustomLayout:
        Button:
            text: 'Back'
            pos: root.width/2-self.width, root.height/2-self.height/2
            size: 200, 100
            on_release: root.manager.transition.direction = 'right'
            on_release: root.manager.current = 'Third'

<CustomLayout>:
    # Changes background. Needs 'before' so that the rectangle is rendered prior to widgets.
    canvas.before:
        Color:
            rgba: 0.945, 0.945, 0.945, 1
        Rectangle:
            pos: self.pos
            size: self.size